### ISSUE TITLE
geojson for each snowpatch from coords provided by Iain Cameron

### ISSUE THREAD

**Issue by SimonFisher92** [SimonFisher92/Scottish_Snow#8]
The geojson provided by Murray informs the ROI for sentinel data download. Currently, this focuses on the cairngorm region. To save time, memory and cost, we should be constructing geojsons for the the list of coordinates provided by Iain, these cover the dominant and important snowpatches in Scotland.

**Comment by murraycutforth** [comment]
FYI @SimonFisher92 I just fed some of the geojsons into this web page [https://geojson.io/#map=2/22.81/14.7](https://geojson.io/#map=2/22.81/14.7) to double check, and it showed me something in the Indian Ocean, because they were expecting (lon, lat) and we currently have it in (lat, lon).

When I googled it there seems like a lot of controversy about which way is correct!

**Comment by murraycutforth** [comment]
Okay I've also realised that maybe a constant offset in lat and lon isn't suitable, because it results in rectangular boxes at high latitudes.

Here's an example using the An Stuc snow patch:

![image](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/378d5113-4d90-4d7c-ab49-8fc0605fa089)

It's down to the trigonometry, the distance per degree of latitude is constant at `2*pi*R / 360`, whereas the distance per degree of longitude is dependent on the latitude (call this theta): `2*pi*R*cos(theta) / 360`. 

At ~56 degrees of latitude, the cos(theta) term equals 0.85, so we should use a longitude offset which is larger by a factor of 1 / 0.85 to get square bounding boxes.

I've implemented this in a way which computes the correction term on the fly so we're not hardcoding 0.85 in there, and it looks like it works:

![image](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/8a9ad9c4-cf75-4046-be91-10e9ae0e01c3)

I think I deleted the branch you made for this so I'll make a new branch/PR with this in.

**Comment by murraycutforth** [comment]
One more question for you @SimonFisher92.

I've just given all the boxes a quick check, and the one which is labelled Nevis Gullies is actually over Aonach Beag. Maybe a mistake in the coords?

![image](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/599b658b-c133-4fbb-a7b3-131083f3b9b3)

**Comment by SimonFisher92** [comment]
Yes, its Aonach Beag! Sorry, that was a carryovder- excellent spot
